services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - wavshare-nw

networks:
  wavshare-nw:
    name: wavshare-nw
